"""
Provenance Guard — Flask API
AI content attribution system for creative writing platforms.
"""

import os
import re
import json
import math
import uuid
import sqlite3
import statistics
from datetime import datetime, timezone

from flask import Flask, request, jsonify, g
from flask_limiter import Limiter
from flask_limiter.util import get_remote_address
from groq import Groq
from dotenv import load_dotenv

load_dotenv()

# ---------------------------------------------------------------------------
# App & rate limiter setup
# ---------------------------------------------------------------------------

app = Flask(__name__)

limiter = Limiter(
    key_func=get_remote_address,
    app=app,
    # Global default — overridden per-route as needed
    default_limits=["200 per day", "50 per hour"],
    storage_uri="memory://",
)

groq_client = Groq(api_key=os.environ.get("GROQ_API_KEY"))

DB_PATH = os.environ.get("DB_PATH", "provenance.db")

# ---------------------------------------------------------------------------
# Database helpers
# ---------------------------------------------------------------------------

def get_db():
    if "db" not in g:
        g.db = sqlite3.connect(DB_PATH)
        g.db.row_factory = sqlite3.Row
    return g.db


@app.teardown_appcontext
def close_db(exc):
    db = g.pop("db", None)
    if db is not None:
        db.close()


def init_db():
    with app.app_context():
        db = get_db()
        db.executescript("""
            CREATE TABLE IF NOT EXISTS submissions (
                content_id   TEXT PRIMARY KEY,
                creator_id   TEXT,
                status       TEXT DEFAULT 'decided',
                created_at   TEXT
            );

            CREATE TABLE IF NOT EXISTS audit_log (
                id            INTEGER PRIMARY KEY AUTOINCREMENT,
                event_id      TEXT UNIQUE,
                event_type    TEXT,
                content_id    TEXT,
                creator_id    TEXT,
                timestamp     TEXT,
                verdict       TEXT,
                confidence    REAL,
                llm_score     REAL,
                stylo_score   REAL,
                label_variant TEXT,
                appeal_reason TEXT,
                status        TEXT
            );
        """)
        db.commit()


# ---------------------------------------------------------------------------
# Signal 1 — LLM Semantic Judge (Groq)
# ---------------------------------------------------------------------------

LLM_SYSTEM_PROMPT = """You are an expert content attribution analyst. Your job is to
assess whether a piece of text was written by a human or generated by an AI system.

Analyze the text holistically — consider: tonal uniformity, structural predictability,
hedging language patterns, transitional phrase overuse, absence of personal
idiosyncrasy, vocabulary variety, and stylistic consistency.

IMPORTANT: Be genuinely calibrated. If you are unsure, say so. A false positive
(calling human work AI-generated) is worse than a false negative on a creative platform.
Lean toward "uncertain" when evidence is mixed.

Respond ONLY with a JSON object, no other text:
{
  "verdict": "human" | "ai" | "uncertain",
  "confidence": <float 0.0–1.0>,
  "reasoning": "<one concise sentence>"
}

Where confidence means:
- For verdict "ai":      probability text is AI-generated
- For verdict "human":   probability text is human-written
- For verdict "uncertain": how confident you are it falls in a gray zone
"""


def llm_signal(text: str) -> dict:
    """
    Returns: {verdict, ai_probability, reasoning}
    ai_probability is always in [0, 1] representing P(AI-generated).
    """
    try:
        response = groq_client.chat.completions.create(
            model="llama-3.3-70b-versatile",
            messages=[
                {"role": "system", "content": LLM_SYSTEM_PROMPT},
                {"role": "user", "content": f"Text to analyze:\n\n{text[:4000]}"},
            ],
            temperature=0.1,
            max_tokens=200,
        )
        raw = response.choices[0].message.content.strip()
        # Strip markdown code fences if present
        raw = re.sub(r"^```(?:json)?\s*", "", raw)
        raw = re.sub(r"\s*```$", "", raw)
        data = json.loads(raw)

        verdict = data.get("verdict", "uncertain")
        conf = float(data.get("confidence", 0.5))
        conf = max(0.0, min(1.0, conf))

        # Convert to P(AI):
        # verdict="ai"      → conf = P(ai)
        # verdict="human"   → conf = P(human), so P(ai) = 1 - conf
        # verdict="uncertain" → center around 0.5, ± small offset based on conf
        if verdict == "ai":
            ai_prob = conf
        elif verdict == "human":
            ai_prob = 1.0 - conf
        else:
            # uncertain: conf tells us how confident the uncertain call is
            # map to [0.35, 0.65]
            ai_prob = 0.5 + (conf - 0.5) * 0.3

        return {
            "verdict": verdict,
            "ai_probability": round(ai_prob, 4),
            "reasoning": data.get("reasoning", ""),
        }

    except Exception as e:
        # Graceful degradation — return neutral uncertain score
        return {
            "verdict": "uncertain",
            "ai_probability": 0.5,
            "reasoning": f"LLM signal unavailable: {str(e)[:80]}",
        }


# ---------------------------------------------------------------------------
# Signal 2 — Stylometric Heuristics
# ---------------------------------------------------------------------------

def _sentences(text: str) -> list[str]:
    """Rough sentence tokenizer."""
    parts = re.split(r"(?<=[.!?])\s+", text.strip())
    return [p for p in parts if len(p.strip()) > 5]


def _words(text: str) -> list[str]:
    return re.findall(r"\b[a-zA-Z']+\b", text.lower())


def _bigrams(words: list[str]) -> list[tuple]:
    return list(zip(words, words[1:]))


def stylo_signal(text: str) -> dict:
    """
    Computes 6 stylometric sub-metrics. Returns ai_probability in [0, 1].
    Higher value = more AI-like.
    """
    sentences = _sentences(text)
    words = _words(text)

    if len(sentences) < 2 or len(words) < 20:
        return {
            "ai_probability": 0.5,
            "sub_metrics": {},
            "note": "Text too short for reliable stylometric analysis",
        }

    sent_lengths = [len(_words(s)) for s in sentences]

    # --- Sub-metric 1: Sentence-length variance (higher variance = more human-like) ---
    sl_var = statistics.variance(sent_lengths) if len(sent_lengths) >= 2 else 0
    # Normalize: variance < 5 is very AI-like, > 60 is very human-like
    sl_score = min(1.0, sl_var / 60.0)

    # --- Sub-metric 2: Type-token ratio (higher = more human-like vocabulary) ---
    ttr = len(set(words)) / len(words)
    # Typical AI: 0.45–0.60, human: 0.60–0.85
    ttr_score = min(1.0, max(0.0, (ttr - 0.40) / 0.45))

    # --- Sub-metric 3: Punctuation density (AI tends to under-punctuate) ---
    punct_count = len(re.findall(r"[,;:\-—\"\'()\[\]{}]", text))
    punct_per_sent = punct_count / len(sentences)
    # Typical AI: 0.5–1.5 per sentence, human: 1.5–5+
    punct_score = min(1.0, max(0.0, (punct_per_sent - 0.5) / 4.0))

    # --- Sub-metric 4: Average sentence length (AI tends longer) ---
    avg_sl = statistics.mean(sent_lengths)
    # Typical AI: 20–30 words, human: 10–20
    # Score: shorter = more human-like
    asl_score = min(1.0, max(0.0, (30.0 - avg_sl) / 20.0))

    # --- Sub-metric 5: Paragraph length variance ---
    paragraphs = [p.strip() for p in text.split("\n\n") if p.strip()]
    if len(paragraphs) >= 2:
        para_lens = [len(_words(p)) for p in paragraphs]
        pv = statistics.variance(para_lens)
        pv_score = min(1.0, pv / 200.0)
    else:
        pv_score = 0.5  # neutral if only one paragraph

    # --- Sub-metric 6: Unique bigram ratio (more unique = more human) ---
    bg = _bigrams(words)
    if bg:
        ubr = len(set(bg)) / len(bg)
        # AI: 0.70–0.85, human: 0.85–0.98
        ubr_score = min(1.0, max(0.0, (ubr - 0.65) / 0.30))
    else:
        ubr_score = 0.5

    sub_metrics = {
        "sentence_length_variance": round(sl_score, 3),
        "type_token_ratio": round(ttr_score, 3),
        "punctuation_density": round(punct_score, 3),
        "avg_sentence_length": round(asl_score, 3),
        "paragraph_length_variance": round(pv_score, 3),
        "unique_bigram_ratio": round(ubr_score, 3),
    }

    # Human-likeness score = mean of sub-metrics
    human_score = statistics.mean(sub_metrics.values())
    ai_probability = round(1.0 - human_score, 4)

    return {
        "ai_probability": ai_probability,
        "sub_metrics": sub_metrics,
        "note": "",
    }


# ---------------------------------------------------------------------------
# Confidence scoring & label generation
# ---------------------------------------------------------------------------

LLM_WEIGHT = 0.75
STYLO_WEIGHT = 0.25

# Thresholds (asymmetric — require stronger evidence to call something AI)
# THRESHOLD_HIGH_AI lowered 0.72 → 0.68 after M4 calibration:
# stylometric TTR/bigram sub-metrics saturate at 1.0 for short texts
# (<5 sentences), systematically under-reporting AI probability.
# Raising LLM weight (0.60→0.75) compensates; threshold adjusted to match.
THRESHOLD_HIGH_AI = 0.68
THRESHOLD_HIGH_HUMAN = 0.28


def blend_signals(llm_ai_prob: float, stylo_ai_prob: float) -> float:
    """
    Weighted blend with asymmetry bias for the uncertain zone.
    Returns final P(AI-generated) in [0, 1].
    """
    blend = LLM_WEIGHT * llm_ai_prob + STYLO_WEIGHT * stylo_ai_prob

    # Asymmetry bias: pull toward uncertain (human-leaning) when signals conflict
    # or blend lands in the gray zone [0.40, 0.65]
    if 0.40 <= blend <= 0.65:
        blend = blend * 0.90  # slight pull toward 0

    return round(max(0.0, min(1.0, blend)), 4)


def label_variant(final_score: float) -> str:
    if final_score >= THRESHOLD_HIGH_AI:
        return "high_ai"
    elif final_score <= THRESHOLD_HIGH_HUMAN:
        return "high_human"
    else:
        return "uncertain"


def make_label(variant: str, confidence: float) -> dict:
    """
    Returns the transparency label shown to readers.
    Three variants with exact text.
    """
    pct = int(round(confidence * 100))

    if variant == "high_ai":
        return {
            "variant": "high_ai",
            "headline": "Likely AI-Generated",
            "body": (
                f"Our system is {pct}% confident this content was generated by an AI tool, "
                "not written by a human. This assessment is based on semantic and structural "
                "analysis and may not be perfect."
            ),
            "call_to_action": (
                "If you are the creator and believe this is incorrect, you can submit an "
                "appeal — we review every one."
            ),
            "display_badge": "AI-Generated",
        }
    elif variant == "high_human":
        return {
            "variant": "high_human",
            "headline": "Likely Human-Written",
            "body": (
                f"Our system is {pct}% confident this content was written by a human. "
                "It shows the kind of stylistic variability and personal voice that "
                "characterizes original human creativity."
            ),
            "call_to_action": None,
            "display_badge": "Human-Written",
        }
    else:  # uncertain
        return {
            "variant": "uncertain",
            "headline": "Origin Uncertain",
            "body": (
                "Our system could not confidently determine whether this content was written "
                "by a human or generated by AI. This may reflect a mix of approaches, an "
                "unusually polished human voice, or limitations of our analysis."
            ),
            "call_to_action": (
                "If you are the creator, you may submit additional context through an appeal "
                "to help clarify attribution."
            ),
            "display_badge": "Origin Uncertain",
        }


# ---------------------------------------------------------------------------
# Audit log helpers
# ---------------------------------------------------------------------------

def write_decision(
    db,
    content_id: str,
    creator_id: str,
    verdict: str,
    confidence: float,
    llm_score: float,
    stylo_score: float,
    lv: str,
):
    now = datetime.now(timezone.utc).isoformat()
    attribution_map = {"ai": "likely_ai", "human": "likely_human", "uncertain": "uncertain"}
    attribution = attribution_map.get(verdict, verdict)

    db.execute(
        """INSERT OR IGNORE INTO submissions (content_id, creator_id, status, created_at)
           VALUES (?, ?, 'decided', ?)""",
        (content_id, creator_id, now),
    )
    db.execute(
        """INSERT INTO audit_log
           (event_id, event_type, content_id, creator_id, timestamp,
            verdict, confidence, llm_score, stylo_score, label_variant, status)
           VALUES (?, 'decision', ?, ?, ?, ?, ?, ?, ?, ?, 'decided')""",
        (
            str(uuid.uuid4()),
            content_id,
            creator_id,
            now,
            verdict,
            confidence,
            llm_score,
            stylo_score,
            lv,
        ),
    )
    db.commit()


def write_appeal(db, content_id: str, creator_id: str, reason: str):
    db.execute(
        "UPDATE submissions SET status = 'under_review' WHERE content_id = ?",
        (content_id,),
    )
    db.execute(
        """INSERT INTO audit_log
           (event_id, event_type, content_id, creator_id, timestamp,
            appeal_reason, status)
           VALUES (?, 'appeal', ?, ?, ?, ?, 'under_review')""",
        (
            str(uuid.uuid4()),
            content_id,
            creator_id,
            datetime.now(timezone.utc).isoformat(),
            reason,
        ),
    )
    db.commit()


# ---------------------------------------------------------------------------
# Routes
# ---------------------------------------------------------------------------

@app.route("/submit", methods=["POST"])
@limiter.limit("10 per minute; 50 per hour; 100 per day")
def submit():
    """
    POST /submit
    Body: { "text": str, "creator_id"?: str, "content_id"?: str }
    Accepts "content" as an alias for "text" for backward compatibility.
    Returns: classification result + transparency label
    """
    body = request.get_json(silent=True) or {}
    # Accept "text" (spec field name) or "content" (alias)
    content = (body.get("text") or body.get("content") or "").strip()

    if not content:
        return jsonify({"error": "Field 'text' is required and must not be empty."}), 400
    if len(content) > 20_000:
        return jsonify({"error": "Content exceeds 20,000 character limit."}), 400

    content_id = body.get("content_id") or str(uuid.uuid4())
    creator_id = body.get("creator_id") or "anonymous"

    # Run both signals
    llm_result = llm_signal(content)
    stylo_result = stylo_signal(content)

    llm_ai_prob = llm_result["ai_probability"]
    stylo_ai_prob = stylo_result["ai_probability"]

    # Blend and score
    final_score = blend_signals(llm_ai_prob, stylo_ai_prob)
    lv = label_variant(final_score)
    label = make_label(lv, final_score)

    # Verdict (internal) and attribution (user-facing alias)
    if lv == "high_ai":
        verdict = "ai"
        attribution = "likely_ai"
    elif lv == "high_human":
        verdict = "human"
        attribution = "likely_human"
    else:
        verdict = "uncertain"
        attribution = "uncertain"

    # Write to audit log
    db = get_db()
    write_decision(db, content_id, creator_id, verdict, final_score, llm_ai_prob, stylo_ai_prob, lv)

    return jsonify({
        "content_id": content_id,
        "attribution": attribution,      # user-facing: "likely_ai" | "likely_human" | "uncertain"
        "verdict": verdict,              # internal alias kept for compatibility
        "confidence": final_score,
        "signals": {
            "llm": {
                "verdict": llm_result["verdict"],
                "ai_probability": llm_ai_prob,
                "reasoning": llm_result["reasoning"],
                "weight": LLM_WEIGHT,
            },
            "stylometric": {
                "ai_probability": stylo_ai_prob,
                "sub_metrics": stylo_result["sub_metrics"],
                "weight": STYLO_WEIGHT,
            },
        },
        "label": label,
        "appeal_endpoint": "/appeal",
    }), 200


@app.route("/appeal", methods=["POST"])
@limiter.limit("5 per hour")
def appeal():
    """
    POST /appeal
    Body: { "content_id": str, "creator_reasoning": str, "creator_id"?: str }
    Accepts "reason" as an alias for "creator_reasoning".
    """
    body = request.get_json(silent=True) or {}
    content_id = body.get("content_id", "").strip()
    creator_id = body.get("creator_id", "").strip()
    # Accept "creator_reasoning" (spec field) or "reason" (alias)
    reason = (body.get("creator_reasoning") or body.get("reason") or "").strip()

    if not content_id:
        return jsonify({"error": "'content_id' is required."}), 400
    if not reason:
        return jsonify({"error": "'creator_reasoning' is required — please explain why you believe the classification is incorrect."}), 400

    db = get_db()
    row = db.execute(
        "SELECT * FROM submissions WHERE content_id = ?", (content_id,)
    ).fetchone()

    if row is None:
        return jsonify({"error": "No submission found with that content_id."}), 404

    if row["status"] == "under_review":
        return jsonify({
            "message": "This content is already under review.",
            "content_id": content_id,
            "status": "under_review",
        }), 200

    effective_creator = creator_id or row["creator_id"]
    write_appeal(db, content_id, effective_creator, reason)

    return jsonify({
        "message": "Your appeal has been received and logged. A human reviewer will assess the original decision and your reasoning.",
        "content_id": content_id,
        "status": "under_review",
        "next_steps": "Appeals are reviewed within 5 business days. You will be notified via the platform when a decision is made.",
    }), 200


@app.route("/log", methods=["GET"])
@limiter.limit("30 per minute")
def audit_log():
    """
    GET /log?limit=20&offset=0
    Returns recent audit log entries.
    """
    try:
        limit = min(int(request.args.get("limit", 20)), 100)
        offset = int(request.args.get("offset", 0))
    except ValueError:
        return jsonify({"error": "limit and offset must be integers"}), 400

    db = get_db()
    rows = db.execute(
        """SELECT * FROM audit_log ORDER BY id DESC LIMIT ? OFFSET ?""",
        (limit, offset),
    ).fetchall()

    total = db.execute("SELECT COUNT(*) FROM audit_log").fetchone()[0]

    entries = [dict(row) for row in rows]
    return jsonify({"total": total, "entries": entries}), 200


@app.route("/health", methods=["GET"])
def health():
    return jsonify({"status": "ok", "service": "provenance-guard"}), 200


# ---------------------------------------------------------------------------
# Entrypoint
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    init_db()
    app.run(debug=True, port=5000)
